# ME:4111 Scientific Computing and Machine Learning 
# Lecture 2: Python Programming - Numpy

### Import numpy package 

In [1]:
import numpy as np

In [3]:
list1 = [1, 2]
list2 = [3,4]
list1 + list2
a1=np.array(list1)
a2=np.array(list2)
a1+a2

array([4, 6])

In [4]:
mylist = [1, 2, 3]
x = np.array(mylist)
print(x)
y = np.array([4, 5, 6])
print(y)
z = np.array([[7, 8, 9], [10, 11, 12]]) # matrix

[1 2 3]
[4 5 6]


In [6]:
z.size


6

In [16]:
A = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
print(A)

B= A.reshape(3,5)
print(B)

print(np.ones((3,2)))

print(np.zeros((3,2)))

print(np.eye(3))

print(np.array([1,2,3]*3))
print(np.repeat([1,2,3],3))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


###   combine arrays

In [9]:
p = np.ones([2,3], int)
print(p,'\n')
#Use vstack to stack arrays in sequence vertically (row wise)
print(np.vstack([p,2*p]),'\n') 
#Use hstack to stack arrays in sequence horizontally (column wise).
print(np.hstack([p,2*p]))

[[1 1 1]
 [1 1 1]] 

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]] 

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


### matrix operations

In [7]:
x = np.array([1,2,3])
print(x)
y = np.array([4, 5, 6])
print(x)
print(y)
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

# dot product
print(x.dot(y)) # dot product  1*4 + 2*5 + 3*6
print(np.dot(x,y))
print(x@y)

[1 2 3]
[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
32
32
32


In [18]:
z = np.array([y, y**2])
print(z)
print(z.T)  #transpose
print(z.dtype)

[[ 4  5  6]
 [16 25 36]]
[[ 4 16]
 [ 5 25]
 [ 6 36]]
int64


### math (statistical) functions

In [20]:
a = np.array([-4, -2, 1, 3, 5])
print(a)
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

#argmax and argmin return the index of the maximum and minimum values in the array.
print(a.argmax(), a.argmin())

[-4 -2  1  3  5]
3
5
-4
0.6
3.2619012860600183
4 0


### Matrix multiplication


In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,7],[7,8,9]])
c = np.matmul(a,b)
print(c,'\n')

# shorthand
c1 = a@b
print(c1,'\n')

# abother way
c2 = a.dot(b)
print(c2,'\n')

[[19 22 25]
 [43 50 57]] 

[[19 22 25]
 [43 50 57]] 

[[19 22 25]
 [43 50 57]] 



### Matrix inversion 

In [31]:
a = np.array([[1,2],[3,4]])
ai = np.linalg.inv(a)
print(ai,'\n\n Inverse of a\n',ai, '\n\n a*ai:\n', ai@a)

[[-2.   1. ]
 [ 1.5 -0.5]] 

 Inverse of a
 [[-2.   1. ]
 [ 1.5 -0.5]] 

 a*ai:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
